<a href="https://colab.research.google.com/github/WMinerva292/WMinerva292/blob/main/Numpy_17_July.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### Manual Creation of the arrays

In [ ]:
list1 = [10, 20, 30, 40, 50, 60]

In [ ]:
list1 * 3

[10, 20, 30, 40, 50, 60, 10, 20, 30, 40, 50, 60, 10, 20, 30, 40, 50, 60]

In [ ]:
twice = []

for value in list1:
  twice.append(value * 2)

In [ ]:
twice

[20, 40, 60, 80, 100, 120]

In [ ]:
arr1 = np.array(list1)

In [ ]:
print(arr1)

[10 20 30 40 50 60]


In [ ]:
arr1 * 2

array([ 20,  40,  60,  80, 100, 120])

In [ ]:
set(arr1)

{10, 20, 30, 40, 50, 60}

In [ ]:
list2 = [10, 20, 30, 40.2, 55, 87, 99, 'Python']

In [ ]:
np.array(list2)

array(['10', '20', '30', '40.2', '55', '87', '99', 'Python'], dtype='<U32')

### Creation of the arrays using functions

- np.arange
- np.ones
- np.zeros
- np.eye
- np.diag
- np.random.random
- np.random.randint
- np.linspace

#### np.arange

In [ ]:
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [ ]:
np.arange(500, 5001)  #(start, stop+1)

array([ 500,  501,  502, ..., 4998, 4999, 5000])

In [ ]:
np.arange(500, 5001, 10)  #(start, stop+1, step)

array([ 500,  510,  520,  530,  540,  550,  560,  570,  580,  590,  600,
        610,  620,  630,  640,  650,  660,  670,  680,  690,  700,  710,
        720,  730,  740,  750,  760,  770,  780,  790,  800,  810,  820,
        830,  840,  850,  860,  870,  880,  890,  900,  910,  920,  930,
        940,  950,  960,  970,  980,  990, 1000, 1010, 1020, 1030, 1040,
       1050, 1060, 1070, 1080, 1090, 1100, 1110, 1120, 1130, 1140, 1150,
       1160, 1170, 1180, 1190, 1200, 1210, 1220, 1230, 1240, 1250, 1260,
       1270, 1280, 1290, 1300, 1310, 1320, 1330, 1340, 1350, 1360, 1370,
       1380, 1390, 1400, 1410, 1420, 1430, 1440, 1450, 1460, 1470, 1480,
       1490, 1500, 1510, 1520, 1530, 1540, 1550, 1560, 1570, 1580, 1590,
       1600, 1610, 1620, 1630, 1640, 1650, 1660, 1670, 1680, 1690, 1700,
       1710, 1720, 1730, 1740, 1750, 1760, 1770, 1780, 1790, 1800, 1810,
       1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920,
       1930, 1940, 1950, 1960, 1970, 1980, 1990, 20

In [ ]:
np.arange(10.0, 51.0, 0.1)

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. , 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9,
       21. , 21.1, 21.2, 21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. ,
       22.1, 22.2, 22.3, 22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1,
       23.2, 23.3, 23.4, 23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2,
       24.3, 24.4, 24.5, 24.6, 24.7, 24.8, 24.9, 25

In [ ]:
np.arange(10, 51, 1.5)

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. , 20.5, 22. , 23.5, 25. ,
       26.5, 28. , 29.5, 31. , 32.5, 34. , 35.5, 37. , 38.5, 40. , 41.5,
       43. , 44.5, 46. , 47.5, 49. , 50.5])

#### np.ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((5,4), dtype = 'int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.ones((5,4)) * 10.5

array([[10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5]])

#### np.zeros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((5,4), dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### **np.eye**

In [ ]:
np.eye(5)  #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3) * 5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

#### **np.diag**

In [ ]:
np.diag([12, 6, 5, 78, 43])

array([[12,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0,  5,  0,  0],
       [ 0,  0,  0, 78,  0],
       [ 0,  0,  0,  0, 43]])

#### **np.random.randint**

In [ ]:
np.random.randint(10)

7

In [ ]:
np.random.randint(10, 51)

36

In [ ]:
np.random.randint(1, 7)

3

In [ ]:
np.random.randint(1000, 10000)

7666

In [ ]:
np.random.randint(1000, 10000, size = 10)

array([7080, 9014, 5047, 9735, 2111, 6497, 7375, 7354, 1249, 2245])

In [ ]:
np.random.randint(100, 501, size = (5,4))

array([[1890, 1970, 1390, 1820],
       [3680, 4370, 3680, 1360],
       [3090, 2910, 3630, 3930],
       [4690, 4470, 3200, 3120],
       [3200, 1990, 3510, 2150]])

#### np.random.random

In [ ]:
np.random.random(5)  #random number between 0.0 and 1.0

array([0.55224608, 0.87760212, 0.1841036 , 0.25246727, 0.35107692])

In [ ]:
np.random.random(5) * 10

array([9.07988883, 3.39555147, 5.7363348 , 5.61085247, 7.51371201])

In [ ]:
np.round((np.random.random(5) * 10), 2)

array([5.24, 1.05, 6.97, 2.1 , 5.65])

### **Array Mathematics**

1. Basic Mathematical Operations (Today)
2. Advanced Mathematical Operations

In [ ]:
arr1 = np.random.randint(10, 51, size = (3,3))
arr2 = np.random.randint(10, 51, size = (3,3))

In [ ]:
arr1

array([[15, 45, 46],
       [34, 18, 13],
       [15, 11, 11]])

In [ ]:
arr2

array([[17, 39, 18],
       [21, 43, 34],
       [45, 46, 40]])

In [ ]:
arr1 + arr2

array([[32, 84, 64],
       [55, 61, 47],
       [60, 57, 51]])

In [ ]:
arr1 + 10

array([[25, 55, 56],
       [44, 28, 23],
       [25, 21, 21]])

In [ ]:
arr1 - arr2

array([[ -2,   6,  28],
       [ 13, -25, -21],
       [-30, -35, -29]])

In [ ]:
arr2 - arr1

array([[  2,  -6, -28],
       [-13,  25,  21],
       [ 30,  35,  29]])

In [ ]:
arr1 * arr2

array([[ 255, 1755,  828],
       [ 714,  774,  442],
       [ 675,  506,  440]])

In [ ]:
arr1 / arr2

array([[0.88235294, 1.15384615, 2.55555556],
       [1.61904762, 0.41860465, 0.38235294],
       [0.33333333, 0.23913043, 0.275     ]])

In [ ]:
arr1 / 2

array([[ 7.5, 22.5, 23. ],
       [17. ,  9. ,  6.5],
       [ 7.5,  5.5,  5.5]])

### **Mean, Sum, Min, Max of the given array**

In [ ]:
arr_1d = np.random.randint(50, 100, size = 10)

In [ ]:
arr_1d

array([96, 57, 57, 96, 96, 95, 50, 59, 56, 83])

In [ ]:
np.mean(arr_1d)

74.5

In [ ]:
np.sum(arr_1d)

745

In [ ]:
np.min(arr_1d)

50

In [ ]:
np.max(arr_1d)

96

In [ ]:
arr = np.random.randint(50, 100, size = (8,6))

In [ ]:
arr

array([[94, 67, 82, 90, 83, 87],
       [90, 77, 84, 71, 74, 56],
       [74, 72, 71, 54, 90, 75],
       [93, 79, 95, 78, 94, 80],
       [61, 81, 97, 65, 80, 75],
       [79, 61, 93, 89, 99, 53],
       [76, 99, 64, 52, 77, 74],
       [52, 87, 94, 91, 75, 79]])

In [ ]:
np.mean(arr, axis = 0)

array([77.375, 77.875, 85.   , 73.75 , 84.   , 72.375])

In [ ]:
np.mean(arr, axis = 1)

array([83.83333333, 75.33333333, 72.66666667, 86.5       , 76.5       ,
       79.        , 73.66666667, 79.66666667])

In [ ]:
np.sum(arr, axis = 0)

array([619, 623, 680, 590, 672, 579])

In [ ]:
np.sum(arr, axis = 1)

array([503, 452, 436, 519, 459, 474, 442, 478])

In [ ]:
np.min(arr, axis = 0)

array([52, 61, 64, 52, 74, 53])

In [ ]:
np.min(arr, axis = 1)

array([67, 56, 54, 78, 61, 53, 52, 52])

In [ ]:
np.max(arr, axis = 0)

array([94, 99, 97, 91, 99, 87])

In [ ]:
np.max(arr, axis = 1)

array([94, 90, 90, 95, 97, 99, 99, 94])

#### **Sorting the Data**

In [ ]:
arr_1d

array([96, 57, 57, 96, 96, 95, 50, 59, 56, 83])

In [ ]:
np.sort(arr_1d)  #arrange the data in ascending order by default

array([50, 56, 57, 57, 59, 83, 95, 96, 96, 96])

In [ ]:
np.sort(arr_1d)[::-1]

array([96, 96, 96, 95, 83, 59, 57, 57, 56, 50])

array([96, 96, 96, 95, 83, 59, 57, 57, 56, 50])

In [ ]:
np.sort(arr, axis = 0)

array([[52, 61, 64, 52, 74, 53],
       [61, 67, 71, 54, 75, 56],
       [74, 72, 82, 65, 77, 74],
       [76, 77, 84, 71, 80, 75],
       [79, 79, 93, 78, 83, 75],
       [90, 81, 94, 89, 90, 79],
       [93, 87, 95, 90, 94, 80],
       [94, 99, 97, 91, 99, 87]])

In [ ]:
np.sort(arr, axis = 1)

array([[67, 82, 83, 87, 90, 94],
       [56, 71, 74, 77, 84, 90],
       [54, 71, 72, 74, 75, 90],
       [78, 79, 80, 93, 94, 95],
       [61, 65, 75, 80, 81, 97],
       [53, 61, 79, 89, 93, 99],
       [52, 64, 74, 76, 77, 99],
       [52, 75, 79, 87, 91, 94]])

In [ ]:
np.sort(arr, axis = 0)[::-1]

array([[94, 99, 97, 91, 99, 87],
       [93, 87, 95, 90, 94, 80],
       [90, 81, 94, 89, 90, 79],
       [79, 79, 93, 78, 83, 75],
       [76, 77, 84, 71, 80, 75],
       [74, 72, 82, 65, 77, 74],
       [61, 67, 71, 54, 75, 56],
       [52, 61, 64, 52, 74, 53]])

### **Indexing and Slicing of the arrays**

In [ ]:
arr_1d

array([90, 70, 66, 50, 85, 52, 72, 99, 61, 90])

In [ ]:
arr_1d[3]

50

In [ ]:
arr_1d[3:7]

array([50, 85, 52, 72])

In [ ]:
arr_1d > 55

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [ ]:
arr_1d[arr_1d > 55]

array([90, 70, 66, 85, 72, 99, 61, 90])

In [ ]:
arr

array([[57, 55, 70, 75, 87, 94],
       [60, 52, 58, 86, 85, 67],
       [62, 67, 77, 91, 61, 96],
       [51, 52, 62, 73, 51, 72],
       [83, 94, 73, 83, 84, 77],
       [87, 76, 96, 92, 66, 63],
       [74, 83, 72, 92, 70, 93],
       [69, 73, 85, 55, 50, 83]])

In [ ]:
arr[2, 1]

67

In [ ]:
arr[2][1]

67

In [ ]:
arr > 55

array([[ True, False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False,  True]])

In [ ]:
arr[arr > 55]

array([57, 70, 75, 87, 94, 60, 58, 86, 85, 67, 62, 67, 77, 91, 61, 96, 62,
       73, 72, 83, 94, 73, 83, 84, 77, 87, 76, 96, 92, 66, 63, 74, 83, 72,
       92, 70, 93, 69, 73, 85, 83])

In [ ]:
arr[1:4, 1:4]

array([[52, 58, 86],
       [67, 77, 91],
       [52, 62, 73]])

### **Array Manipulation**

- np.vstack
- np.hstack
- np.column_stack
- np.hsplit
- np.vsplit

In [ ]:
arr4 = np.random.randint(10, 51, size = (5,5))
arr5 = np.random.randint(10, 51, size = (5,5))

In [ ]:
arr4

array([[45, 19, 47, 45, 33],
       [14, 24, 21, 38, 15],
       [24, 21, 23, 49, 16],
       [18, 46, 15, 42, 44],
       [39, 31, 15, 16, 11]])

In [ ]:
arr5

array([[28, 18, 32, 40, 50],
       [25, 21, 49, 10, 41],
       [35, 25, 29, 39, 27],
       [39, 32, 39, 19, 21],
       [18, 29, 43, 18, 46]])

In [ ]:
np.vstack((arr4, arr5))

array([[45, 19, 47, 45, 33],
       [14, 24, 21, 38, 15],
       [24, 21, 23, 49, 16],
       [18, 46, 15, 42, 44],
       [39, 31, 15, 16, 11],
       [28, 18, 32, 40, 50],
       [25, 21, 49, 10, 41],
       [35, 25, 29, 39, 27],
       [39, 32, 39, 19, 21],
       [18, 29, 43, 18, 46]])

In [ ]:
np.hstack((arr4, arr5))

array([[45, 19, 47, 45, 33, 28, 18, 32, 40, 50],
       [14, 24, 21, 38, 15, 25, 21, 49, 10, 41],
       [24, 21, 23, 49, 16, 35, 25, 29, 39, 27],
       [18, 46, 15, 42, 44, 39, 32, 39, 19, 21],
       [39, 31, 15, 16, 11, 18, 29, 43, 18, 46]])

In [ ]:
np.concatenate((arr4, arr5), axis = 0)  #similar to vstack

array([[45, 19, 47, 45, 33],
       [14, 24, 21, 38, 15],
       [24, 21, 23, 49, 16],
       [18, 46, 15, 42, 44],
       [39, 31, 15, 16, 11],
       [28, 18, 32, 40, 50],
       [25, 21, 49, 10, 41],
       [35, 25, 29, 39, 27],
       [39, 32, 39, 19, 21],
       [18, 29, 43, 18, 46]])

In [ ]:
np.concatenate((arr4, arr5), axis = 1)  #similar to hstack

array([[45, 19, 47, 45, 33, 28, 18, 32, 40, 50],
       [14, 24, 21, 38, 15, 25, 21, 49, 10, 41],
       [24, 21, 23, 49, 16, 35, 25, 29, 39, 27],
       [18, 46, 15, 42, 44, 39, 32, 39, 19, 21],
       [39, 31, 15, 16, 11, 18, 29, 43, 18, 46]])

In [ ]:
arr_1 = np.arange(1, 6)

In [ ]:
arr_1

array([1, 2, 3, 4, 5])

In [ ]:
arr4

array([[45, 19, 47, 45, 33],
       [14, 24, 21, 38, 15],
       [24, 21, 23, 49, 16],
       [18, 46, 15, 42, 44],
       [39, 31, 15, 16, 11]])

In [ ]:
np.column_stack((arr4, arr_1))

array([[45, 19, 47, 45, 33,  1],
       [14, 24, 21, 38, 15,  2],
       [24, 21, 23, 49, 16,  3],
       [18, 46, 15, 42, 44,  4],
       [39, 31, 15, 16, 11,  5]])

In [ ]:
np.row_stack((arr4, arr_1))

array([[45, 19, 47, 45, 33],
       [14, 24, 21, 38, 15],
       [24, 21, 23, 49, 16],
       [18, 46, 15, 42, 44],
       [39, 31, 15, 16, 11],
       [ 1,  2,  3,  4,  5]])

In [ ]:
arr

array([[57, 55, 70, 75, 87, 94],
       [60, 52, 58, 86, 85, 67],
       [62, 67, 77, 91, 61, 96],
       [51, 52, 62, 73, 51, 72],
       [83, 94, 73, 83, 84, 77],
       [87, 76, 96, 92, 66, 63],
       [74, 83, 72, 92, 70, 93],
       [69, 73, 85, 55, 50, 83]])

In [ ]:
arr10, arr11 = np.hsplit(arr, 2)

[array([[57, 55, 70],
        [60, 52, 58],
        [62, 67, 77],
        [51, 52, 62],
        [83, 94, 73],
        [87, 76, 96],
        [74, 83, 72],
        [69, 73, 85]]),
 array([[75, 87, 94],
        [86, 85, 67],
        [91, 61, 96],
        [73, 51, 72],
        [83, 84, 77],
        [92, 66, 63],
        [92, 70, 93],
        [55, 50, 83]])]

In [ ]:
np.vsplit(arr, 2)

[array([[57, 55, 70, 75, 87, 94],
        [60, 52, 58, 86, 85, 67],
        [62, 67, 77, 91, 61, 96],
        [51, 52, 62, 73, 51, 72]]),
 array([[83, 94, 73, 83, 84, 77],
        [87, 76, 96, 92, 66, 63],
        [74, 83, 72, 92, 70, 93],
        [69, 73, 85, 55, 50, 83]])]